# GitLab CI configuration
#
# This configured GitLab CI to run three jobs: one for unit tests, one to
# create a release build, and one to build and publish documentation.

stages:
  - test
  - build
  - docs
  - publish

test:
  stage: test
  image: rust
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  script:
    - cargo test

style:
  stage: test
  image: rust
  script:
    - rustup component add rustfmt clippy
    - cargo fmt --check
    - cargo clippy -- --deny warnings

build:
  stage: build
  image: alpine
  before_script:
    - apk add cargo
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/mdbook-docker-run

docs:
  stage: docs
  image: alpine
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    MDBOOK_PREPROCESSOR__DOCKER_RUN__COMMAND: "target/release/mdbook-docker-run"
    RUST_LOG: debug
  before_script:
    - apk add mdbook
  script:
    - mdbook build
  artifacts:
    paths:
      - target/book

pages:
  stage: publish
  image: alpine
  script:
    - mv target/book public
    - mv target/release/mdbook-docker-run public/mdbook-docker-run-amd64
  artifacts:
    paths:
      - public
  only:
    - main
